### ISSUE TITLE
fillMode uses fixed value

### ISSUE THREAD

**Issue by hmhv** [cats-oss/Sica#20]
Hi. Thank you for good library.

Is there any reason why fillMode is fixed value?

https://github.com/cats-oss/Sica/blob/3adaee7047f5a896cb3c57da136e7b73a9383672/Sica/Source/Animator.swift#L110

and why isRemovedOnCompletion's default value is false? even though CAAnimation's default value is true.

https://github.com/cats-oss/Sica/blob/3adaee7047f5a896cb3c57da136e7b73a9383672/Sica/Source/Animator.swift#L103

日本語の説明は以下を参考してください。
https://qiita.com/hachinobu/items/57d4c305c907805b4a53#comment-0709844b92e4f16057aa

**Comment by funzin** [comment]
In latest version 0.40, FillMode can be set to `func run` parameter. 
https://github.com/cats-oss/Sica/releases/tag/0.4.0

>and why isRemovedOnCompletion's default value is false? even though CAAnimation's default value is true.

I read your question on the article. You're right!
In the present situation, default value is set to `isRemovedOnCompletion: Bool = false` and  `fillMode: FillMode = FillMode.forwards` in order to leave an apparent animationLayer.

**Comment by hmhv** [comment]
@funzin 
Thank you for FillMode fix!! 👍
